name: wallet-tracker
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - requests
  - python-telegram-bot
  - sqlalchemy  # Example for database management
  - pip:
      - solana  # For Solana wallet tracking
      - python-dotenv  # For environment variables
      - apscheduler  # For scheduling tasks
